"           _
"    __   _(X)_ __ ___  _ __ ____
"    \ \ / / | '_ ` _ \|X`__/  __|
"  _  \ V /| | | |X| | | |  | (X_
" (_)  \X/ |_|_| |_| |_|_|  \____|
"
" hapidznur's .vimrc file
" https://www.github.com/hapidznur/dotfiles

set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)
"-------------------=== Code/Project navigation ===-------------
Plugin 'scrooloose/nerdtree'                " Project and file navigation
Plugin 'Xuyuanp/nerdtree-git-plugin'        " NerdTree git functionality
Plugin 'vim-airline/vim-airline'            " Lean & mean status/tabline for vim
Plugin 'vim-airline/vim-airline-themes'     " Themes for airline
Plugin 'mileszs/ack'                        " SliverSearch
Plugin 'junegunn/fzf.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'godlygeek/tabular'                  "markdown
Plugin 'plasticboy/vim-markdown'            "markdown
"-------------------=== Other ===-------------------------------
Plugin 'tpope/vim-fugitive'                   " Git Operation:s
Plugin 'kien/rainbow_parentheses.vim'       " Rainbow Parentheses
Plugin 'sickill/vim-monokai'
"-------------------=== Snippets support ===--------------------
Plugin 'cakebaker/scss-syntax.vim'          " Sassy CSS
"-------------------=== Languages support ===-------------------
Plugin 'scrooloose/nerdcommenter'           " Easy code documentation
Plugin 'mitsuhiko/vim-sparkup'              " Sparkup(XML/jinja/htlm-django/etc.) support

"-------------------=== Python  ===-----------------------------
Plugin 'tell-k/vim-autopep8'                " autopep8
Plugin 'Chiel92/vim-autoformat'             " auto format for python
" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype on
filetype plugin on
filetype indent on

" -----------
" Konfigurasi
" -----------
set autoindent
set autoread
set autowrite
set backspace=indent,eol,start
set encoding=utf8
set expandtab
set formatoptions=tcqn1 
" t - autowrap normal text
" c - autowrap comments
" q - gq formats comments
" n - autowrap lists
" 1 - break _before_ single-letter words
" 2 - use indenting from 2nd line of para
set hlsearch
set linebreak
set nobackup
set nonumber
set notitle
set nowritebackup
set printoptions=paper:letter " US paper
set ruler                   " Show row/col and percentage
set scroll=4                " Number of lines to scroll with ^U/^D
set scrolloff=15            " Keep cursor away from this many chars top/bot
set sessionoptions-=options " Don't save runtimepath in Vim session (see tpope/vim-pathogen docs)
set shiftround              " Shift to certain columns, not just n spaces
set shortmess+=A            " Don't bother me when a swapfile exists
set showbreak=              " Show for lines that have been wrapped, like Emacs
set showmatch               " Hilight matching braces/parens/etc.
set sidescrolloff=3         " Keep cursor away from this many chars left/right
set smartcase       
set shiftwidth=4
set softtabstop=4
set suffixes+=.pyc
set tabstop=4
set visualbell t_vb=
set wildmenu
set wildmode=list:longest,full
set wildignore=".class,~,o,*.pyc,.git,node_modules

" use mouse not in insert mode
silent! set mouse =nvc
silent! nohlsearch
" -------------
" Plugin Konfig
" -------------

" FZF (replaces Ctrl-P, FuzzyFinder and Command-T)
set rtp+=/usr/local/opt/fzf
set rtp+=~/.fzf
nmap ; :Buffers<CR>
nmap <Leader>r :Tags<CR>
nmap <Leader>t :Files<CR>
nmap <Leader>a :Ag<CR>

" Tell ack.vim to use ag (the Silver Searcher) instead
let g:ackprg = 'ag --vimgrep'

" NERDTree PLugin
nmap \e :NERDTreeToggle<cr>
let g:NERDTreeWinSize=17
" Ignore files in NERDTree
let NERDTreeIgnore=['\.pyc$', '\.pyo$', '__pycache__$']
let NERDTreeWinSize=40
" Load NERDTree only if vim is run without arguments
autocmd VimEnter * if !argc() | NERDTree | endif 


" vim-airline buat warna-warni
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'


" Theme Konfig 
set background=dark
let g:rehash256 = 1
set t_Co=256  " vim-sublime-monokai now only support 256 colours in terminal.
syntax on
colorscheme monokai

" GitGutter styling to use · instead of +/-
let g:gitgutter_sign_added = '∙'
let g:gitgutter_sign_modified = '∙'
let g:gitgutter_sign_removed = '∙'
let g:gitgutter_sign_modified_removed = '∙'

" -----------
" Auto Konfig
" -----------
augroup vimrc
    autocmd!
    au BufNewFile,BufRead *.csv     setf csv
    au BufNewFile,BufRead *.ini     setf conf
    au BufNewFile,BufRead *.json    set ft=json tw=0
    au BufNewFile,BufRead *.sass    setf sass
    au BufNewFile,BufRead *.scss    setf scss
    au BufNewFile,BufRead *.xml     setlocal ft=xml  ts=2 sw=2 et
    au BufNewFile,BufRead *.zshrc   setf zsh number
    au BufNewFile,BufRead *.yml,*.yaml setlocal ft=yaml ts=2 sw=2 sts=2
    au BufNewFile,BufRead *.py setlocal ts=4 sw=4 sts=4
    au BufNewFile,BufRead *.blade.php,*.php,*.htm,*.html, setlocal ts=2 sw=2 sts=2
    au FileType json setlocal conceallevel=0 foldmethod=syntax foldlevel=999
    au Filetype gitcommit setlocal tw=80
    au FileType gitcommit setlocal nolist ts=4 sts=4 sw=4 noet
    au FileType make setlocal nolist ts=4 sts=4 sw=4 noet
augroup END
"
" --------
" Key Maps
" --------
command! Q q
command! W w
" ctrl + s As Save
noremap <silent> <C-S> 		    :update<CR>
vnoremap <silent> <C-S> <C-C>	:update<CR>
inoremap <silent> <C-S> <C-O>   	:update<CR>
" disable indent bawaan dari copy paste
noremap <F8> :setl noai  nocin nosi inde=<CR>

" ----------------
" Local Vim Konfig
" ---------------
if filereadable(expand("~/.vimlocal"))
	source ~/.vimlocal
endif


